repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: make pytest_check
        language: system
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: make ruff_check
        language: system
        pass_filenames: false
      - id: black
        name: black
        entry: make black_check
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: make mypy_check
        language: system
        pass_filenames: false
      - id: tomlsort
        name: tomlsort
        entry: make tomlsort_check
        language: system
        pass_filenames: false
{%- if cookiecutter.include_sqlalchemy == "y" %}
      - id: paracelsus
        name: paracelsus
        entry: make paracelsus_check
        language: system
        pass_filenames: false
{% endif %}
