name: Black Formatting

on:
  push:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Python Version from File
        id: python_version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v3
        with:
          python-version: {% raw %}${{ steps.python_version.outputs.version }}{% endraw %}

      - name: Install Dependencies
        run: make install

      - name: Test Formatting
        run: make black_check
